version: '2'

services:
  web:
    build: .
    volumes:
      - .:/app
      - bundle:/bundle
    environment:
      - BUNDLE_PATH=/bundle
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - 3000:3000

volumes:
  bundle:
